version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acp
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  acp-service:
    image: acp_submission_image
    ports:
      - "8080:8080"
    environment:
      ACP_POSTGRES: jdbc:postgresql://postgres:5432/acp?currentSchema=s2347484
      ACP_S3: http://localstack:4566
      ACP_DYNAMODB: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    depends_on:
      - localstack
      - postgres